### ISSUE TITLE
Proposal for single library

### ISSUE THREAD

**Issue by Visgean** [pipermerriam/ethereum-ipc-client#8]
Hi, I was looking for a library to communicate with geth node and I came across your two projects and pyethapp. I think that you these repositories are very useful but I think it would be better if they would be all merged into one library with common interface... 

Something like this: 

```
from ethereum_client import Client, IPCTransport

client = Client(IPCTransport)
```

this would make it more easier to switch between each interface...

**Comment by Visgean** [comment]
or is this https://github.com/pipermerriam/web3.py what I am talking about?

**Comment by pipermerriam** [comment]
The current plan is for web3.py to replace these client libraries.

**Comment by Visgean** [comment]
oh, ok this makes sense. Btw I don't think that web3 is the best name for that repository - its kind of hard to discover.. it would be better to somehow emphasize that its about ethereum...
